### ISSUE TITLE
[FR] - Machine Readability

### ISSUE THREAD

**Issue by oldcryptogeek** [input-output-hk/cardano-node#1084]
**Describe the feature you'd like**
A standard output format for key and certificate creation that can be parsed easily by third party software.  I propose to use JSON for this purpose, although the current situation is very close to YAML already.

**Describe alternatives you've considered**
Having no standard and letting the community manage on it's own.

**Additional context / screenshots**
Some examples of current output.  

```yaml
type: Node operator verification key
title: Stake pool operator key
cbor-hex:
 5820cb078f5782cb2d196c516d9350e2ae08b0a25e8003c59f1c31df3c6e622518f4
```
```yaml
type: Node operational certificate issue counter
title: Next certificate issue number: 0
cbor-hex:
 00
```
