### ISSUE TITLE
[FR] - Provide support for running cardano-node with docker also as a block-producer

### ISSUE THREAD

**Issue by matiwinnetou** [input-output-hk/cardano-node#1307]
*External*   otherwise.

**Describe the feature you'd like**
A clear and detailed description of what you are suggesting.
We (FreeDOM Cardano Stake Pool) would like to run relays and block-producing node with docker. We have successfully managed to run relay nodes via docker based on documentation from: https://github.com/input-output-hk/cardano-node/blob/master/nix/docker.nix

However, we do not see an option to pass critical parameters to be able to run block-producing node via docker, namely:

- --shelley-kes-key
- --shelley-vrf-key
- --shelley-operational-certificate

**Comment by matiwinnetou** [comment]
Am I missing something or this feature is really missing?

**Comment by kevinhammond** [comment]
Passed on for comment.  It may simply be a configuration issue

**Comment by rdlrt** [comment]
I kinda put it as usage issue, we shouldn't force a docker container running with config that depends on blockchain's status.
It is very easy to add those 3 params for someone wanting to do so with a container.

**Comment by matiwinnetou** [comment]
@rdlrt but if a docker image is build without ability to pass those params, how would it be possible to do this without change in: docker.nix. Maybe I am thick but to me it looks like cosmetic changes in docker.nix and passing those optional params to cardano-node are necessary.

**Comment by matiwinnetou** [comment]
@rdlrt We can create own docker image or overload entrypoint but these are all wokrarounds, isn't better to simply allow a user to pass shelly certicates and keys as variables?

**Comment by matiwinnetou** [comment]
or am I misunderstanding that those files would automagically be picked from configuration directory?

**Comment by rhyslbw** [comment]
The image was designed to allow the optional arguments to be passed as the run _command_, as  there are some conventions that allow config to be mounted into a standard location. We might revisit this, but for now: 

(truncated for brevity) 

`docker-compose.yaml`
``` yaml
services:
  cardano-node:
    image: inputoutput/cardano-node
    volumes:
      - node-db:/data/db
      - ./my-node-config:/configuration 
      - ./delegate-keys:/delegate-keys
    command: [
      "--shelley-kes-key", "/configuration/kes.skey",
      "--shelley-vrf-key", "/configuration/vrf.skey",
      "--shelley-operational-certificate", "/configuration/node.cert",
    ]
  ...
volumes:
  node-db:
```

``` console
docker run -v node-db:/data/db inputoutput/cardano-node /
  --shelley-kes-key /configuration/kes.skey /
  --shelley-vrf-key /configuration/vrf.skey /
  
```
