### ISSUE TITLE
[BUG] - Docker image cannot start

### ISSUE THREAD

**Issue by got3nks** [input-output-hk/cardano-node#1648]
**docker-compose.yml**

```
services:
  cardano-node:
    image: inputoutput/cardano-node:master
    environment:
      - NETWORK=mainnet
    volumes:
      - /home/cardano/.cardano-byron/node-db:/data/db
      - /home/cardano/.cardano-byron/node-ipc:/ipc
```

**root@server:/home/cardano# docker-compose pull**
`Pulling cardano-node         ... done`

**root@server:/home/cardano# docker-compose up -d cardano-node**
```
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS                      PORTS                                                                        NAMES
4cec64ed96a0        inputoutput/cardano-node:master   "/nix/store/k61q02rx…"   20 minutes ago      Exited (1) 20 minutes ago                                                                                cardano_cardano-node_1_1d12c9b893ca
```

**root@server:/home/cardano# docker logs -f 4cec64ed96a0**

```
Starting cardano-node run: /nix/store/yz88yhv8xlr4lvhm17kx0gbvym388xqp-cardano-node-exe-cardano-node-1.18.0/bin/cardano-node run
--config /nix/store/dl0z53787sbnx3593igxqh9ia6p4v0fr-config-0.json
--database-path /data/db
--topology /nix/store/mb0zb61472xp1hgw3q9pz7m337rmfx7f-topology.yaml
--host-addr 127.0.0.1
--port 3001
--socket-path /ipc/node.socket





..or, once again, in a single line:
/nix/store/yz88yhv8xlr4lvhm17kx0gbvym388xqp-cardano-node-exe-cardano-node-1.18.0/bin/cardano-node run --config /nix/store/dl0z53787sbnx3593igxqh9ia6p4v0fr-config-0.json --database-path /data/db --topology /nix/store/mb0zb61472xp1hgw3q9pz7m337rmfx7f-topology.yaml --host-addr 127.0.0.1 --port 3001 --socket-path /ipc/node.socket
Listening on http://127.0.0.1:12798
There was an error parsing the genesis file: /nix/store//nix/store/3678ccikas3q16jcqcghwviqsd5k9wjx-mainnet-byron-genesis.json Error: GenesisDataIOError /nix/store//nix/store/3678ccikas3q16jcqcghwviqsd5k9wjx-mainnet-byron-genesis.json: openBinaryFile: does not exist (No such file or directory)
```
