### ISSUE TITLE
[BUG] - Error when executing cardano-cli over node.socket

### ISSUE THREAD

**Issue by DiazRock** [input-output-hk/cardano-node#2720]
**Area**
*Creation of Staking Pool*

**Summary**
I want to create a staking pool. I'm following the steps from the [official documentation](https://docs.cardano.org/projects/cardano-node/en/latest/), and working with the testnet first. But when I use cardano-cli to query the testnet, I get the next error:
`cardano-cli: encodeFailure: local state query: using acquire without a Point must be conditional on negotiating v8 of the node-to-client protocol CallStack (from HasCallStack): error, called at src/Ouroboros/Network/Protocol/LocalStateQuery/Codec.hs:79:7 in ouroborosnetwork0.1.0.04jeKomdFdXlCG0PGFQPwJS:Ouroboros.Network.Protocol.LocalStateQuery.Codec`

I assume that is related to node.socket file. Because other kind of operations (create keys or address) works fine for me.

**Steps to reproduce**
First I will list the software that I use and their versions:
1. Docker-compose version 1.28.5, build c4eb3a1f
2. cardano-cli 1.27.0 - linux-x86_64 - ghc-8.10 git rev 709a259403c0ba03988950c0e4696d7457a3a5aa
3. The cardano [official docker image](https://hub.docker.com/layers/inputoutput/cardano-node/1.27.0/images/sha256-02779484dc23731cdbea6388920acc6ddd8e40c03285bc4f9c7572a91fe2ee08?context=explore)

1. This is the docker-compose.yml that I'm using
```yml
version: "3"
services:
  elasbit-relay1: 
    image: inputoutput/cardano-node:latest
    container_name: elasbit-relay1
    ports: 
      - 12798:12798
    volumes:
      - $PWD/testnet/:/configuration
      - $PWD/relay1/:/relay1_logs
    command: [
              "run",
              "--topology /configuration/testnet-topology.json",
              "--database-path /relay1_logs/db",
              "--socket-path /relay1_logs/node.socket",
              "--host-addr 0.0.0.0",
              "--port 3001",
              "--config /configuration/testnet-config.json" 
            ]
    restart: unless-stopped
  elasbit-relay2: 
    image: inputoutput/cardano-node:latest
    container_name: elasbit-relay2
    ports: 
      - 12799:12798
    volumes:
      - $PWD/testnet/:/configuration
      - $PWD/relay2:/relay2_logs
    command: [
              "run",
              "--topology /configuration/testnet-topology.json",
              "--database-path /relay2_logs/db",
              "--socket-path /relay2_logs/node.socket",
              "--host-addr 0.0.0.0",
              "--port 3001",
              "--config /configuration/testnet-config.json"
            ]
    restart: unless-stopped
```
2. I got the following env variable pointing to node.socket of `elasbit_relay1` cardano node: CARDANO_NODE_SOCKET_PATH
3. I do `sudo -E cardano-cli query protocol-parameters --shelley-mode --testnet-magic 1097911063 --out-file protocol.json`
4. I get the error: 
`cardano-cli: encodeFailure: local state query: using acquire without a Point must be conditional on negotiating v8 of the node-to-client protocol CallStack (from HasCallStack): error, called at src/Ouroboros/Network/Protocol/LocalStateQuery/Codec.hs:79:7 in ouroborosnetwork0.1.0.04jeKomdFdXlCG0PGFQPwJS:Ouroboros.Network.Protocol.LocalStateQuery.Codec`

**Expected behavior**
I want to get in `protocol.json` the info related to network. I want to execute queries to the network using `cardano-cli`.

**System info:**
- Distributor ID:	Ubuntu
- Description:	Ubuntu 18.04.5 LTS
- Release:	18.04
- Codename:	bionic

**How far have I come**:
I tried with a node outside a container. But I get the same error. I tried with only a container (elasbit_relay1), and the same result. There is a suggestion in a [forum discussion](https://forum.cardano.org/t/error-when-executing-cardano-cli-over-node-socket/62015), about supress the `--shelley-mode`. But in that case I get an error related to Byron era.
