### ISSUE TITLE
[BUG] - Extremely slow synchronization on high end dedi

### ISSUE THREAD

**Issue by Displee** [input-output-hk/cardano-node#3175]
**External**

**Area**
*Other*

**Summary**
I'm using `cardano-db-sync`.

It took me 5 days to sync the Cardano blockchain to 99.50%. It's extremely slow on a high end dedicated server.
Server specs:
```
- Software
   Debian 10 (Buster)
- CPU
    Intel(R) Xeon(R) CPU E3-1270 v6 @ 3.80GHz
    Cores : 8
    Cache : 8192KB 
- Memory
   2x 16384MB (32GB)
- Storage
   2x 1TB HDD (2TB)
- Internet speed
   1 GB/ps
```
I noticed it barely uses my CPU. It does however use some RAM. Here's a htop snapshopt:
![putty_ILSoafW6sw](https://user-images.githubusercontent.com/12080880/132340584-35b32d34-68a4-4055-ac23-2d952c0008ff.png)

But that's mostly the `postgres` service...

Here's a speedtest during synchronization:
![Speedtest](https://i.imgur.com/rShC4Pq.png)

I can't lay my finger on the issue. The logs do not contain anything outstanding either. I've restarted everything multiple times, some times after two days, some times after a day, but no effect. It's still extremely slow. Here's the latest log:
https://displee.com/upload/cardano-db-sync-log.txt

My docker compose: https://displee.com/upload/db-sync-docker-compose.yml
I added 2 lines to the docker compose (in the postgres service):
```
ports:
      - 5432:5432
```
Does anyone else have experienced the same issue before? Can anyone help me understand why this is going so slow?

**Comment by gitmachtl** [comment]
Try to sync with only one or two nodes in your topology, it slows down if you fill it up with like 20 nodes in there.

**Comment by ggcaponetto** [comment]
I am experiencing the same issue on:
```
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
CPU(s):                          10
On-line CPU(s) list:             0-9
Thread(s) per core:              1
Core(s) per socket:              10
CPU family:                      23
Model:                           49
Model name:                      AMD EPYC 7282 16-Core Processor
CPU MHz:                         2794.748
Hypervisor vendor:               KVM
Ram:                              60G
```

and this dockefile:
```
version: "3.9"

x-141x-cardano-node-db:
  &141x-cardano-node-db
  type: bind
  source: ./141x-cardano-node/db
  target: /opt/cardano/data
x-141x-nft:
  &141x-nft
  type: bind
  source: ./141x-cardano-node/141x-nft
  target: /141x-nft

x-141x-couchdb:
  &141x-couchdb
  type: bind
  source: ./setup/couchdb
  target: /opt/couchdb/data
x-141x-couchdb-config:
  &141x-couchdb-config
  type: bind
  source: ./setup/couchdb-config/local.ini
  target: /opt/couchdb/etc/local.ini
x-141x-snapshots:
  &141x-snapshots
  type: bind
  source: /postgres-snapshots
  target: /postgres-snapshots

services:
  socketio:
    image: "ggcaponetto/141x-socketio:latest"
    container_name: socketio
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=cexplorer
      - PG_PASSWORD=v8hlDV0yMAHHlIurYupj
      - PG_PORT=5432
      - PORT=5003
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5003:5003"
  backend:
    image: "ggcaponetto/141x-backend:latest"
    container_name: backend
    environment:
      - PG_USER=postgres
      - PG_HOST=postgres
      - PG_DATABASE=cexplorer
      - PG_PASSWORD=v8hlDV0yMAHHlIurYupj
      - PG_PORT=5432
      - PORT=5001
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "5001:5001"
  app:
    image: "ggcaponetto/141x-explorer:latest"
    container_name: app
    environment:
      - PORT=5000
      - NODE_ENV=production
      - REACT_APP_CARDANO_MAINNET_HOST=app.141x.io
      - REACT_APP_CARDANO_TESTNET_HOST=app.141x-testnet.io

      - REACT_APP_GATEWAY_MAINNET_HOST=https://gateway.141x.io
      - REACT_APP_GATEWAY_MAINNET_PORT=443
      - REACT_APP_GATEWAY_TESTNET_HOST=https://gateway.141x-testnet.io
      - REACT_APP_GATEWAY_TESTNET_PORT=443

      - REACT_APP_BACKEND_MAINNET_HOST=https://backend.141x.io
      - REACT_APP_BACKEND_MAINNET_PORT=443
      - REACT_APP_BACKEND_TESTNET_HOST=https://backend.141x-testnet.io
      - REACT_APP_BACKEND_TESTNET_PORT=443

      - REACT_APP_WALLET_MAINNET_HOST=https://wallet.141x.io
      - REACT_APP_WALLET_MAINNET_PORT=443
      - REACT_APP_WALLET_TESTNET_HOST=https://wallet.141x-testnet.io
      - REACT_APP_WALLET_TESTNET_PORT=443

      - REACT_APP_SOCKETIO_MAINNET_HOST=https://socketio.141x.io
      - REACT_APP_SOCKETIO_MAINNET_PORT=443
      - REACT_APP_SOCKETIO_TESTNET_HOST=https://socketio.141x-testnet.io
      - REACT_APP_SOCKETIO_TESTNET_PORT=443

      - REACT_APP_BACKEND_ALT_HOST=http://localhost
      - REACT_APP_BACKEND_ALT_PORT=5001

      - REACT_APP_WALLET_ALT_HOST=http://localhost
      - REACT_APP_WALLET_ALT_PORT=5002

      - REACT_APP_SOCKETIO_ALT_HOST=http://localhost
      - REACT_APP_SOCKETIO_ALT_PORT=5003

      - REACT_APP_FUNDS_ADDRESS_TESTNET=addr_test1qqd774n8vhp8a8h66ftsfl0t5rvj870glafjgx2zywe84nmw87cey4nwnxkyfqwa736c4zmmh02t0vz2qlkzlqqugf5qhk9wcl
      - REACT_APP_FUNDS_ADDRESS_MAINNET=addr1q9dta74g2axw39zf440w67vd0dyq7md4360q4cah3ev72q2hy6re7yfwwt4y246wh3r867l6sjnnlzwseug2t4jp97ps2ajcnh

      - REACT_APP_SPONSOR_ADDRESS_TESTNET=addr_test1qqd774n8vhp8a8h66ftsfl0t5rvj870glafjgx2zywe84nmw87cey4nwnxkyfqwa736c4zmmh02t0vz2qlkzlqqugf5qhk9wcl
      - REACT_APP_SPONSOR_ADDRESS_MAINNET=addr1q9dta74g2axw39zf440w67vd0dyq7md4360q4cah3ev72q2hy6re7yfwwt4y246wh3r867l6sjnnlzwseug2t4jp97ps2ajcnh

      - REACT_APP_PAYMENT_ADDRESS_TESTNET=addr_test1qz7767fwe38ch62hq0wyk443lvafa6z6vh7f9sdgx0r078nw87cey4nwnxkyfqwa736c4zmmh02t0vz2qlkzlqqugf5q6e0m2m
      - REACT_APP_PAYMENT_ADDRESS_MAINNET=addr1qxhhqyjy27uy8pytltwep63yc2dapn6k77r5ynx968p0lczhy6re7yfwwt4y246wh3r867l6sjnnlzwseug2t4jp97ps8n5psw
    ports:
      - "5000:5000"
    deploy:
      restart_policy:
        condition: on-failure
  wallet:
    image: "ggcaponetto/141x-wallet:latest"
    container_name: wallet
    environment:
      - NODE_ENV=production
      - PORT=5002
      - CARDANO_WALLET_HOST=http://cardano-wallet
      - CARDANO_WALLET_PORT=8090
    ports:
      - "5002:5002"
    deploy:
      restart_policy:
        condition: on-failure
  nft:
    image: "ggcaponetto/141x-cardano-node:latest"
    container_name: nft
    volumes:
      - <<: *141x-cardano-node-db
      - <<: *141x-nft
      - node-ipc:/node-ipc
    depends_on:
      - couchdb
    environment:
      - NETWORK=mainnet
      - CARDANO_NODE_SOCKET_PATH=/node-ipc/node.socket
      - PORT=5004
      - NFT_WALLET_ADDRESS_MAINNET=addr1qymwupddlpcdrzsjsyv5k2swwg2a9npmctmlfz0ukxeyz7jhy6re7yfwwt4y246wh3r867l6sjnnlzwseug2t4jp97pswdu7hd
      - NFT_WALLET_ADDRESS_TESTNET=addr_test1qz7767fwe38ch62hq0wyk443lvafa6z6vh7f9sdgx0r078nw87cey4nwnxkyfqwa736c4zmmh02t0vz2qlkzlqqugf5q6e0m2m
      - NFT_FEE_CALCULATION_ADDRESS_MAINNET=addr1qymwupddlpcdrzsjsyv5k2swwg2a9npmctmlfz0ukxeyz7jhy6re7yfwwt4y246wh3r867l6sjnnlzwseug2t4jp97pswdu7hd
      - NFT_FEE_CALCULATION_ADDRESS_TESTNET=addr_test1qz7767fwe38ch62hq0wyk443lvafa6z6vh7f9sdgx0r078nw87cey4nwnxkyfqwa736c4zmmh02t0vz2qlkzlqqugf5q6e0m2m
      - NFT_PROFIT_MARGIN_MAINNET=1000000
      - NFT_PROFIT_MARGIN_TESTNET=1000000

      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdano9090shouldbefine
      - COUCHDB_HOST=couchdb
      - COUCHDB_PORT=5984
      - COUCHDB_PROTOCOL=http

      - ADMIN_USER=admin
      - ADMIN_PASSWORD=couchisbetterthan99
      - PUBLICUSER_USER=publicuser
      - PUBLICUSER_PASSWORD=publicpass
    ports:
      - "5004:5004"
    deploy:
      restart_policy:
        condition: on-failure
  couchdb:
    image: "couchdb:latest"
    container_name: couchdb
    volumes:
      - <<: *141x-couchdb
      - <<: *141x-couchdb-config
    environment:
      - ERL_FLAGS="-couch_ini /etc/default.ini /opt/couchdb/etc/local.ini"
      - NETWORK=mainnet
      - COUCHDB_USER=couchdb
      - COUCHDB_PASSWORD=couchdano9090shouldbefine
      - COUCHDB_HOST=localhost
      - COUCHDB_PORT=5984
      - COUCHDB_PROTOCOL=http
      - ADMIN_USER=admin
      - ADMIN_PASSWORD=couchisbetterthan99
      - PUBLICUSER_USER=publicuser
      - PUBLICUSER_PASSWORD=publicpass
    ports:
      - "5984:5984"
    deploy:
      restart_policy:
        condition: on-failure
  ipfs-gateway:
    image: "ipfs/go-ipfs:latest"
    container_name: ipfs-gateway
    volumes:
      - ipfs-docker-staging:/export
      - ipfs-docker-data:/data/ipfs
    ports:
      - "8080:8080"
      - "8081:4001"
      - "8082:5001"
    deploy:
      restart_policy:
        condition: on-failure
  cardano-wallet:
    image: inputoutput/cardano-wallet:2021.9.9
    container_name: cardano-wallet
    volumes:
      - ./setup/cardano-db-sync/config/network/${NETWORK:-mainnet}:/config
      - node-ipc:/node-ipc
      - wallet-mainnet-db:/wallet-mainnet-db
    ports:
      - 8090:8090
    entrypoint: [ ]
    command: bash -c "($$CMD)"
    environment:
      CMD: "cardano-wallet serve --node-socket /node-ipc/node.socket --database /wallet-mainnet-db --listen-address 0.0.0.0 --mainnet"
      NETWORK: "mainnet"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"
  postgres:
    image: postgres:${POSTGRES_VERSION:-11.5-alpine}
    container_name: postgres
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    ports:
      - ${POSTGRES_PORT:-5432}:5432
    secrets:
      - postgres_db
      - postgres_password
      - postgres_user
    shm_size: '2gb'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.31.0}
    container_name: cardano-node
    environment:
      - NETWORK=${NETWORK:-mainnet}
    volumes:
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  cardano-db-sync-extended:
    image: inputoutput/cardano-db-sync:${CARDANO_DB_SYNC_VERSION:-12.0.0-pre3}
    container_name: cardano-db-sync-extended
    command: [
        "--config", "/config/cardano-db-sync/config.json",
        "--socket-path", "/node-ipc/node.socket"
    ]
    environment:
      - EXTENDED=true
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - RESTORE_SNAPSHOT=${RESTORE_SNAPSHOT:-}
      - RESTORE_RECREATE_DB=${RESTORE_RECREATE_DB:-}
      - NETWORK=mainnet
    depends_on:
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - ./setup/cardano-db-sync/config/network/${NETWORK:-mainnet}:/config
      - db-sync-data:/var/lib/cdbsync
      - node-ipc:/node-ipc
      - <<: *141x-snapshots
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    ports:
      - 5433:5433
    restart: unless-stopped
  kong-migration:
    image: kong:latest
    container_name: kong-migration
    command: "kong migrations bootstrap"
    restart: on-failure
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    links:
      - kong-database
    depends_on:
      - kong-database
  kong:
    image: kong:latest
    container_name: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    volumes:
      - ./setup/gateway/config:/config
    restart: unless-stopped
    depends_on:
      - kong-migration
  konga:
    image: pantsel/konga
    container_name: konga
    environment:
      - NODE_ENV=production
    ports:
      - 1337:1337
    restart: unless-stopped
    depends_on:
      - kong-database
  swag:
    image: ghcr.io/linuxserver/swag
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - URL=141x.io
      - SUBDOMAINS=app,backend,wallet,konga,kong,socketio
      - VALIDATION=http
      # - CERTPROVIDER=zerossl
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - DUCKDNSTOKEN= #optional
      # - EMAIL=ggcaponetto@gmail.com
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
      - MAXMINDDB_LICENSE_KEY= #optional
    volumes:
      - ./setup/rev-proxy/config:/config
    ports:
      - 443:443
      - 80:80 #optional
    depends_on:
      - app
      - wallet
      - backend
      - kong
      - konga
    restart: unless-stopped

secrets:
  postgres_db:
    file: ./setup/cardano-db-sync/placeholder-secrets/postgres_db
  postgres_password:
    file: ./setup/cardano-db-sync/placeholder-secrets/postgres_password
  postgres_user:
    file: ./setup/cardano-db-sync/placeholder-secrets/postgres_user
networks:
  default:
    name: 141x
volumes:
  node-db:
  postgres-data:
  node-ipc:
  ipfs-docker-staging:
  ipfs-docker-data:
  wallet-mainnet-db:
  wallet-testnet-db:
  db-sync-data:
```
