### ISSUE TITLE
Shutting down.. NoDbMarkerAndNotEmpty "/data/db/protocolMagicId"

### ISSUE THREAD

**Issue by magick93** [input-output-hk/cardano-node#3231]
# Background

I'm attempting to run cardano-node and cardano-submit-api in a kubernetes pod. 

I have been able to successfully run ardano-node and cardano-submit-api using the docker-compose.yml file that is included in this repository. Thank you for including this, it is very helpful.

# Versions

I've tried using both `inputoutput/cardano-node:1.29.0` and `inputoutput/cardano-node:1.30.0` but get the same error with both.

# Issue
I have essentially created a kuberenetes deployment yml file based on this docker-compose file. 

However, when I run it, I am getting the below error.  See the logs.

I'm unsure what is causing this, or how to solve it.

# logs

```
kubectl logs -f cardano-node-88fd8d5c6-26jjn -c cardano-node
Starting: /nix/store/h45pyw7wvsbrwan2rmnqw3cqccj8rv98-cardano-node-exe-cardano-node-1.30.0/bin/cardano-node run
--config /nix/store/4b0rmqn24w0yc2yvn33vlawwdxa3a71i-config-0-0.json
--database-path /data/db
--topology /nix/store/mb0zb61472xp1hgw3q9pz7m337rmfx7f-topology.yaml
--host-addr 0.0.0.0
--port 3001
--socket-path /ipc/node.socket





+RTS
-N2
-A16m
-qg
-qb
--disable-delayed-os-memory-return
-RTS
..or, once again, in a single line:
/nix/store/h45pyw7wvsbrwan2rmnqw3cqccj8rv98-cardano-node-exe-cardano-node-1.30.0/bin/cardano-node run --config /nix/store/4b0rmqn24w0yc2yvn33vlawwdxa3a71i-config-0-0.json --database-path /data/db --topology /nix/store/mb0zb61472xp1hgw3q9pz7m337rmfx7f-topology.yaml --host-addr 0.0.0.0 --port 3001 --socket-path /ipc/node.socket      +RTS -N2 -A16m -qg -qb --disable-delayed-os-memory-return -RTS
Listening on http://127.0.0.1:12798
[cardano-:cardano.node.networkMagic:Notice:5] [2021-09-21 02:38:33.46 UTC] NetworkMagic 764824073
[cardano-:cardano.node.basicInfo.protocol:Notice:5] [2021-09-21 02:38:33.46 UTC] Byron; Shelley
[cardano-:cardano.node.basicInfo.version:Notice:5] [2021-09-21 02:38:33.46 UTC] 1.30.0
[cardano-:cardano.node.basicInfo.commit:Notice:5] [2021-09-21 02:38:33.46 UTC] 191b91eec3c7d845a55347781329d50bf36871d7
[cardano-:cardano.node.basicInfo.nodeStartTime:Notice:5] [2021-09-21 02:38:33.46 UTC] 2021-09-21 02:38:33.466280391 UTC
[cardano-:cardano.node.basicInfo.systemStartTime:Notice:5] [2021-09-21 02:38:33.46 UTC] 2017-09-23 21:44:51 UTC
[cardano-:cardano.node.basicInfo.slotLengthByron:Notice:5] [2021-09-21 02:38:33.46 UTC] 20s
[cardano-:cardano.node.basicInfo.epochLengthByron:Notice:5] [2021-09-21 02:38:33.46 UTC] 21600
[cardano-:cardano.node.basicInfo.slotLengthShelley:Notice:5] [2021-09-21 02:38:33.46 UTC] 1s
[cardano-:cardano.node.basicInfo.epochLengthShelley:Notice:5] [2021-09-21 02:38:33.46 UTC] 432000
[cardano-:cardano.node.basicInfo.slotsPerKESPeriodShelley:Notice:5] [2021-09-21 02:38:33.46 UTC] 129600
[cardano-:cardano.node.basicInfo.slotLengthAllegra:Notice:5] [2021-09-21 02:38:33.46 UTC] 1s
[cardano-:cardano.node.basicInfo.epochLengthAllegra:Notice:5] [2021-09-21 02:38:33.46 UTC] 432000
[cardano-:cardano.node.basicInfo.slotsPerKESPeriodAllegra:Notice:5] [2021-09-21 02:38:33.46 UTC] 129600
[cardano-:cardano.node.basicInfo.slotLengthMary:Notice:5] [2021-09-21 02:38:33.46 UTC] 1s
[cardano-:cardano.node.basicInfo.epochLengthMary:Notice:5] [2021-09-21 02:38:33.46 UTC] 432000
[cardano-:cardano.node.basicInfo.slotsPerKESPeriodMary:Notice:5] [2021-09-21 02:38:33.46 UTC] 129600
[cardano-:cardano.node.basicInfo.slotLengthAlonzo:Notice:5] [2021-09-21 02:38:33.46 UTC] 1s
[cardano-:cardano.node.basicInfo.epochLengthAlonzo:Notice:5] [2021-09-21 02:38:33.46 UTC] 432000
[cardano-:cardano.node.basicInfo.slotsPerKESPeriodAlonzo:Notice:5] [2021-09-21 02:38:33.46 UTC] 129600
[cardano-:cardano.node.addresses:Notice:5] [2021-09-21 02:38:33.46 UTC] [SocketInfo 0.0.0.0:3001]
[cardano-:cardano.node.diffusion-mode:Notice:5] [2021-09-21 02:38:33.46 UTC] InitiatorAndResponderDiffusionMode
[cardano-:cardano.node.dns-producers:Notice:5] [2021-09-21 02:38:33.46 UTC] [DnsSubscriptionTarget {dstDomain = "relays-new.cardano-mainnet.iohk.io", dstPort = 3001, dstValency = 1}]
[cardano-:cardano.node.ip-producers:Notice:5] [2021-09-21 02:38:33.46 UTC] IPSubscriptionTarget {ispIps = [], ispValency = 0}

Shutting down..
NoDbMarkerAndNotEmpty "/data/db/protocolMagicId"

cardano-node: Missing "/data/db/protocolM
```

# Relevant Kubernetes resource

```yml

apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: cardano-node
  name: cardano-node
spec:
  replicas: 1
  serviceName: {{ template "cardano-submit-api.fullname" . }}-svc
  selector:
    matchLabels:
      io.kompose.service: cardano-node
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: cardano-node
    spec:
      containers:
        - image: inputoutput/cardano-node:1.29.0
          name: cardano-node
          env:
            - name: NETWORK
              value: mainnet
          resources: {}
          volumeMounts:
            - mountPath: /data/db
              name: {{ template "cardano-submit-api.fullname" . }}-node-db
            - mountPath: /ipc
              name: {{ template "cardano-submit-api.fullname" . }}-node-ipc

        - image: inputoutput/cardano-submit-api:1.30.0
          name: cardano-submit-api
          ports:
            - containerPort: 8090
          resources: {}
          env:
            - name: NETWORK
              value: mainnet
          volumeMounts:
            - mountPath: /node-ipc
              name: {{ template "cardano-submit-api.fullname" . }}-node-ipc
        
      restartPolicy: Always
      volumes:
        - name: {{ template "cardano-submit-api.fullname" . }}-node-db
          persistentVolumeClaim:
            claimName: {{ template "cardano-submit-api.fullname" . }}-node-db
        - name: {{ template "cardano-submit-api.fullname" . }}-node-ipc
          persistentVolumeClaim:
            claimName: {{ template "cardano-submit-api.fullname" . }}-node-ipc


```

# Update

It seems the container eventually comes right, which makes me think its something to do with the startup order of the `cardano-node` and the `cardano-submit-api`.

Rather than wait for luck to resolve this startup order issue, I could probably resolve this by using livilness and readiness checks on the containers. 

### Attempts

I've tried adding the following, unfortunately it didnt resolve the issue:

#### Run privileged

I tried adding the following:

```yml
securityContext:
            # runAsUser: 1000
            allowPrivilegeEscalation: true
```

#### Run with a startup probe

```yml
        spec:
      containers:
        - image: inputoutput/cardano-node:1.29.0
          name: cardano-node
          startupProbe:
            initialDelaySeconds: 3
            exec:
              command:
              - cardano-cli
              - query
              - tip
```

Does anyone have an example of either a http or cli command I can call on the `cardano-node` or the `cardano-submit-api`?
