### ISSUE TITLE
[BUG] - cardano-summit-api error

### ISSUE THREAD

**Issue by kraymond37** [input-output-hk/cardano-node#3248]
**Internal/External**
*External*

**Area**
*Other*   cardano-submit-api

**Summary**
cardano-submit-api reports an error.

**Steps to reproduce**
1. 
```
cat txsigned.temp | jq .
{
  "type": "Tx MaryEra",
  "description": "",
  "cborHex": "83a40081825820f6a1e4779860adea2069b6aae924e1b85d9a753c32a8ce7138ea881f58d01cf600018282581d60f56f59da91e684e2a1b06d0d395a788f1092e55c003b66c699fbc8921a0098968082581d6028418552557353564f9f330e530b16ed7aa2e6158140bcf337dfb6001a3affabcf021a000287b1031a0247cd20a10081825820f5c52ccb0fe3391b250cda1fd5385e2c9b25ecc8538b8403215cd2177f74d5995840cc723d594903bbed4176b1d637ae92855ee23e3143b2a8bd9d0a9fedceaeb3c8564b07f817a725d5bd017c74153939f0434244f3798bf9e33b7a5840e49d4504f6"
}
```
2.
```
xxd -r -p <<< $(jq .cborHex txsigned.temp) > tx.submit-api.raw
```
3.
```
curl -H "Content-Type: application/cbor" -X POST --data-binary @./tx.submit-api.raw http://localhost:8091/api/submit/tx
```
see error `[cardano-tx-submit:Info:54] [2021-09-26 02:12:49.01 UTC] txSubmitPost: received 233 bytes
MuxError MuxBearerClosed "<socket: 15> closed when reading data, waiting on next header True"`
This is all, there are no more logs.

4.
```
CARDANO_NODE_SOCKET_PATH=/ipc/node.socket cardano-cli transaction submit --tx-file /data/txsigned.temp --testnet-magic 1097911063
```
Tx submitted successfully.

**Expected behavior**
Submit tx successfully.

**System info (please complete the following information):**
I use the official docker images.
```
version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.29.0
    environment:
      NETWORK:
    volumes:
      - node-${NETWORK}-db:/data
      - node-ipc:/ipc
      - node-config:/nix/store
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

  cardano-submit-api:
    image: inputoutput/cardano-submit-api
    environment:
      - NETWORK=${NETWORK:-testnet}
    depends_on:
      - cardano-node
    volumes:
      - node-ipc:/node-ipc
    ports:
      - "8091:8090"
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

volumes:
  node-mainnet-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/node-mainnet-db
  node-testnet-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/node-testnet-db
  node-alonzo-purple-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/node-alonzo-purple-db
  wallet-mainnet-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/wallet-mainnet-db
  wallet-testnet-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/wallet-testnet-db
  wallet-alonzo-purple-db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/wallet-alonzo-purple-db
  node-ipc:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/node-ipc
  node-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /data/ada/node-config
```
