### ISSUE TITLE
[BUG] - cardano node 1.30.1 memory error

### ISSUE THREAD

**Issue by kraymond37** [input-output-hk/cardano-node#3279]
**Internal/External**
*External*

**Summary**
Upgrade cardano-node to 1.30.1, the node reports an error:
```
...
...
...
[27946f21:cardano.node.ChainDB:Notice:631] [2021-10-08 02:53:21.82 UTC] Chain extended, new tip: f6f93fb295f1891fb671391ca5a9dd49b7d68c4b81bf5040b3254fd081a2c4be at slot 42061485
[27946f21:cardano.node.ChainDB:Notice:631] [2021-10-08 02:53:23.07 UTC] Chain extended, new tip: 0b895ca0c7099d6cc6d0687d9205d9195d08589859ee29ece4c7981565afdd9b at slot 42063469
[27946f21:cardano.node.ChainDB:Notice:631] [2021-10-08 02:53:24.32 UTC] Chain extended, new tip: 007068534dec66bc3b46dcf8cdffd6d6fb639af1e404a362665dafc53c9c46c4 at slot 42065293
[27946f21:cardano.node.ChainDB:Notice:631] [2021-10-08 02:53:25.62 UTC] Chain extended, new tip: ba494c71b468573cba5e7b2efe0b710132882175bfdfe4ed9038fa6085a333fc at slot 42066884
[27946f21:cardano.node.ChainDB:Notice:631] [2021-10-08 02:53:26.88 UTC] Chain extended, new tip: 920955df26281037e4393aeaa50c4646906ce5b001d13715a6e69616b418cdda at slot 42068643
[27946f21:cardano.node.ChainDB:Notice:631] [2021-10-08 02:53:28.13 UTC] Chain extended, new tip: a6c3f132d0757d4aad4ba12c75fcba6e44cb8d9cd7bc01faf0de286e09f741bf at slot 42070495
cardano-node: internal error: Unable to commit 1048576 bytes of memory
    (GHC version 8.10.5 for x86_64_unknown_linux)
    Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```

**Steps to reproduce**
1. docker-compose.yml
```
version: "3.5"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.30.1
    environment:
      NETWORK:
    volumes:
      - node-${NETWORK}-db:/data
      - node-ipc:/ipc
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        compress: "true"
        max-file: "10"
        max-size: "50m"

volumes:
  node-mainnet-db:
  node-testnet-db:
  node-alonzo-purple-db:
  wallet-mainnet-db:
  wallet-testnet-db:
  wallet-alonzo-purple-db:
  node-ipc:
  node-config:
```
2. `NETWORK=mainnet docker-compose up -d`
3. `docker logs -f --tail 10 ada_cardano-node_1`
4. Wait for a while, See error
```
cardano-node: internal error: Unable to commit 1048576 bytes of memory
    (GHC version 8.10.5 for x86_64_unknown_linux)
    Please report this as a GHC bug:  https://www.haskell.org/ghc/reportabug
```
memory info
```
free -h
              total        used        free      shared  buff/cache   available
Mem:           7.7G        7.5G        112M        708K         35M         47M
Swap:            0B          0B          0B
```

**System info (please complete the following information):**
- OS Name: [aws ec2]
- mem:
```
$free -h
              total        used        free      shared  buff/cache   available
Mem:           7.7G        230M        5.4G        560K        2.1G        7.2G
Swap:            0B          0B          0B
```
