### ISSUE TITLE
[BUG] - Can't connect to testnet with the released config files - Node version 1.31.0

### ISSUE THREAD

**Issue by ggcaponetto** [input-output-hk/cardano-node#3375]
**Internal/External**
*External*

**Area**
*Sync*
**Summary**
I expect the cardano-node to sync on the testnet

**Steps to reproduce**
Spin up the following docker compose file.

```yaml
version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:${CARDANO_NODE_VERSION:-1.31.0}
    container_name: cardano-node
    volumes:
      - ./setup/cardano-db-sync/config/network/testnet:/config
      - node-db:/data/db
      - node-ipc:/ipc
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    command: [
        "run",
        "--topology /config/cardano-node/topology.json",
        "--config /config/cardano-node/config.json",
        "--socket-path /ipc/node.socket",
        "--database-path /data/db"
    ]
networks:
  default:
    name: 141x
volumes:
  node-db:
  node-ipc:
```

**Expected behavior**
cardano-node starts syncing

**Error**
```
[a4c23206:cardano.node.DnsSubscription:Notice:343] [2021-11-18 08:54:42.68 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt Start, destination 54.250.11.33:3001
[a4c23206:cardano.node.DnsSubscription:Warning:77] [2021-11-18 08:54:42.91 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions
[a4c23206:cardano.node.DnsSubscription:Notice:343] [2021-11-18 08:54:42.91 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Connection Attempt End, destination 54.250.11.33:3001 outcome: ConnectSuccess
[a4c23206:cardano.node.DnsSubscription:Error:343] [2021-11-18 08:54:43.14 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Application Exception: 54.250.11.33:3001 HandshakeError (Refused NodeToNodeV_7 "version data mismatch: NodeToNodeVersionData {networkMagic = NetworkMagic {unNetworkMagic = 1097911063}, diffusionMode = InitiatorAndResponderDiffusionMode} /= NodeToNodeVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}, diffusionMode = InitiatorAndResponderDiffusionMode}")
[a4c23206:cardano.node.ErrorPolicy:Notice:75] [2021-11-18 08:54:43.14 UTC] IP 54.250.11.33:3001 ErrorPolicySuspendConsumer (Just (ApplicationExceptionTrace (HandshakeError (Refused NodeToNodeV_7 "version data mismatch: NodeToNodeVersionData {networkMagic = NetworkMagic {unNetworkMagic = 1097911063}, diffusionMode = InitiatorAndResponderDiffusionMode} /= NodeToNodeVersionData {networkMagic = NetworkMagic {unNetworkMagic = 764824073}, diffusionMode = InitiatorAndResponderDiffusionMode}")))) 200s
[a4c23206:cardano.node.DnsSubscription:Warning:77] [2021-11-18 08:54:52.68 UTC] Domain: "relays-new.cardano-testnet.iohkdev.io" Failed to start all required subscriptions

```

**System info (please complete the following information):**
- Ubuntu 21
-  cardano-node 1.31.0

**Additional context**
The mounted volume for the config contains [these files](https://hydra.iohk.io/build/7654130/download/1/index.html), which are listed in the release notes of [version 1.31.0](https://github.com/input-output-hk/cardano-node/releases/tag/1.31.0). I had to change the hashes of all 3 genesis files before being able to start the node. I am wondering if the config/topology are up to date for that given version. Thanks!
