### ISSUE TITLE
[FR] - Add health endpoint

### ISSUE THREAD

**Issue by stefiix92** [input-output-hk/cardano-node#4103]
**External**

**Area**
*Monitoring*  

**Describe the feature you'd like**
Add a health endpoint that will indicate whether the node is synced or not. I find it useful to automatically deregister from Load Balancer based on health check status.

Healthy (synced) node should return HTTP code 200, otherwise 400.

**Additional context / screenshots**
Add a metric also to Prometheus metrics to be able better monitor healthy nodes

**Comment by danielbjornadal** [comment]
Not a fix, but a temporary solution.

You can check if `node.socket` exist. The socket will not be created before node is fully synced.

Linux command: `test -S <socket>`
Kubernetes readinessProbe:
```
        readinessProbe:
          initialDelaySeconds: 60
          exec:
            command:
              - test
              - -S
              - <socket>
```
