### ISSUE TITLE
Move tracers into config `.yaml` file

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#443]
Tracers should be specified from the config `.yaml` file as having them on the command line is cumbersome.

**Comment by CodiePP** [comment]
it probably would make sense to type them like: `Maybe Severity`. This way we can distinguish whether they are on or off, and what the minimum severity is that will pass the filter on this trace.
what do you think?

**Comment by Jimbo4350** [comment]
@CodiePP  I was thinking of a dictionary structure like this:
```
TraceBlockFetchClient:
    On: True
    Severity: Debug
    Verbosity: MaximumVerbosity
```
Or we can add an additional constructor to `Severity` (maybe `Off` for example) and we can simplify the configuration to:
```
TraceBlockFetchClient:
    Severity: Off
    Verbosity: MaximumVerbosity
```
or 
```
TraceBlockFetchClient:
    Severity: Debug
    Verbosity: MaximumVerbosity
```

**Comment by CodiePP** [comment]
> I was thinking of a dictionary structure per tracer in the yaml file like this:
> 
> ```
> TraceBlockFetchClient:
>     On: True
>     Severity: Debug
>     Verbosity: MaximumVerbosity
> ```

or `enabled: True` ?    can turn on/off the complete trace
currently, verbosity is a global switch. But, this would give more flexibility if it can be defined per trace.
and "Severity" could be renamed to `MinSeverity`? it is actually the minimum severity level that passes the filter.
you are right, a structure is much better to describe all these options.

**Comment by Jimbo4350** [comment]
```
TraceBlockFetchClient:
    Enabled: True
    MinSeverity: Debug
    Verbosity: MaximumVerbosity
```
Made the changes you suggested above :+1: 

I'd like to make verbosity definable per trace unless there is a reason not to.
