### ISSUE TITLE
Improve tracer control in config `.yaml` files

### ISSUE THREAD

**Issue by Jimbo4350** [input-output-hk/cardano-node#473]
Following from https://github.com/input-output-hk/cardano-node/issues/443#issuecomment-569678510 we would like the following improvement for tracers:

```
TraceBlockFetchClient:
    Enabled: True
    MinSeverity: Debug
    Verbosity: MaximumVerbosity
```
with implicit defaults for `MinSeverity` and `Verbosity` as requested by @CodiePP (https://github.com/input-output-hk/cardano-node/issues/443#issuecomment-569692969)
