### ISSUE TITLE
docker-compose: accessing node socket from host machine

### ISSUE THREAD

**Issue by nazrhom** [input-output-hk/cardano-node#4913]
Hello,
I seem to be unable to access the cardano node socket from my host machine.

I am running the following compose setup:

```
version: "3.9"

services:
  cardano-node:
    image: inputoutput/cardano-node:1.35.4
    volumes:
      - ./devnet:/devnet
    environment:
      - CARDANO_NODE_SOCKET_PATH=/devnet/ipc/node.socket # used by cardano-cli
      [...]
    command:
      [ "run" ...   ]

```

I can successfully start-up the node through `docker-compose up -d`, and from within the `cardano-node` container I can run `cardano-cli` commands correctly. 
From the host machine, I can see the `./devnet/ipc/node.socket` being created. However, if I try to point my local cardano-cli to that node and run any command, I get: `cardano-cli: Network.Socket.connect: <socket: 13>: does not exist (Connection refused)`
