### ISSUE TITLE
CAD-708 Cardano prometheus metrics disappeared with cardano-node 1.7.0

### ISSUE THREAD

**Issue by jbgi** [input-output-hk/cardano-node#619]
using following config:
```yaml
ApplicationName: cardano-sl
ApplicationVersion: 1
AssetLockedSrcAddress: []
Burst: 0
CacheParameter: 500
CriticalCQ: 0.654321
CriticalCQBootstrap: 0.8888
CriticalForkThreshold: 3
Enabled: false
FixedTimeCQ: 3600
GenesisHash: c6a004d3d178f600cd8caa10abbebe1549bef878f0665aea2903472d5abf7323
HandshakeTimeout: 30000
LastKnownBlockVersion-Alt: 0
LastKnownBlockVersion-Major: 1
LastKnownBlockVersion-Minor: 0
MemPoolLimitTx: 200
MessageCacheTimeout: 30
NetworkConnectionTimeout: 15000
NetworkDiameter: 18
NodeHostAddress: ''
NodeId: 2
NodePort: 3001
NonCriticalCQ: 0.8
NonCriticalCQBootstrap: 0.95
NumCoreNodes: 7
Period: ''
PollDelay: 1800000000
Protocol: RealPBFT
Rate: 0
RecoveryHeadersMessage: 2200
RequiresNetworkMagic: RequiresNoMagic
ResponseTimeout: 30000000
Servers:
- 0.pool.ntp.org
- 2.pool.ntp.org
- 3.pool.ntp.org
SlotLength: 20000
StreamWindow: 2048
TraceBlockFetchClient: false
TraceBlockFetchDecisions: true
TraceBlockFetchProtocol: false
TraceBlockFetchProtocolSerialised: false
TraceBlockFetchServer: false
TraceChainDb: true
TraceChainSyncBlockServer: false
TraceChainSyncClient: false
TraceChainSyncHeaderServer: false
TraceChainSyncProtocol: false
TraceDNSResolver: false
TraceDNSSubscription: false
TraceErrorPolicy: false
TraceForge: true
TraceIpSubscription: false
TraceLocalChainSyncProtocol: false
TraceLocalTxSubmissionProtocol: false
TraceLocalTxSubmissionServer: false
TraceMempool: true
TraceMux: false
TraceTxInbound: false
TraceTxOutbound: false
TraceTxSubmissionProtocol: false
TracingVerbosity: MaximalVerbosity
TurnOnLogMetrics: true
TurnOnLogging: true
ViewMode: SimpleView
defaultBackends:
- KatipBK
defaultScribes:
- - StdoutSK
  - stdout
hasEKG: 12788
hasPrometheus:
- 172.31.19.133
- 12798
minSeverity: Debug
options:
  cfokey:
    value: Release-1.0.0
  mapBackends:
    cardano.node-metrics:
    - EKGViewBK
    - kind: EKGViewBK
      name: LiveViewBackend
    cardano.node.BlockFetchDecision:
    - kind: UserDefinedBK
      name: LiveViewBackend
    cardano.node.metrics.ChainDB:
    - EKGViewBK
    - kind: EKGViewBK
      name: LiveViewBackend
    cardano.node.peers.BlockFetchDecision:
    - kind: UserDefinedBK
      name: LiveViewBackend
  mapSubtrace:
    "#ekgview":
      contents:
      - - contents: cardano.epoch-validation.benchmark
          tag: Contains
        - - contents: ".monoclock.basic."
            tag: Contains
      - - contents: cardano.epoch-validation.benchmark
          tag: Contains
        - - contents: diff.RTS.cpuNs.timed.
            tag: Contains
      - - contents: "#ekgview.#aggregation.cardano.epoch-validation.benchmark"
          tag: StartsWith
        - - contents: diff.RTS.gcNum.timed.
            tag: Contains
      subtrace: FilterTrace
    "#messagecounters.aggregation":
      subtrace: NoTrace
    "#messagecounters.ekgview":
      subtrace: NoTrace
    "#messagecounters.katip":
      subtrace: NoTrace
    "#messagecounters.monitoring":
      subtrace: NoTrace
    "#messagecounters.switchboard":
      subtrace: NoTrace
    benchmark:
      contents:
      - GhcRtsStats
      - MonotonicClock
      subtrace: ObservableTrace
    cardano.epoch-validation.utxo-stats:
      subtrace: NoTrace
    cardano.node-metrics:
      subtrace: Neutral
rotation:
  rpKeepFilesNum: 10
  rpLogLimitBytes: 5000000
  rpMaxAgeHours: 24
setupBackends:
- AggregationBK
- KatipBK
- EKGViewBK
setupScribes:
- scFormat: ScText
  scKind: StdoutSK
  scName: stdout
  scRotation: 
```
what need to be adjusted?
