### ISSUE TITLE
Run by docker and long time has no /data/node.socket file

### ISSUE THREAD

**Issue by islishude** [input-output-hk/cardano-node#761]
<img width="1792" alt="截屏2020-04-04 下午5 50 38" src="https://user-images.githubusercontent.com/24730006/78423983-f3792500-769c-11ea-945a-fef26c947ace.png">

<img width="689" alt="截屏2020-04-04 下午5 52 02" src="https://user-images.githubusercontent.com/24730006/78424000-1277b700-769d-11ea-9c6d-728d417a28f0.png">

<img width="1791" alt="截屏2020-04-04 下午5 53 23" src="https://user-images.githubusercontent.com/24730006/78424021-31764900-769d-11ea-9085-adc90e9366d5.png">

db-sync connects node takes 5 mins

my config

```yaml
version: "3.5"

services:
  postgres:
    image: postgres:11.5-alpine
    environment:
      - POSTGRES_LOGGING=true
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: on-failure

  node:
    # cardano-node 1.8.0
    image: inputoutput/cardano-node:64c2778c61245dcda13eaf16a2e0738dfacb7a16
    environment:
      - NETWORK=mainnet
    volumes:
      - cardano-node:/data
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  dbsync:
    # cardano-db-sync 1.4.0
    image: inputoutput/cardano-db-sync:be2fb8ae73c3ad872de0ad80621bca4718b64b25
    environment:
      - NETWORK=mainnet
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - node
      - postgres
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    volumes:
      - cardano-node:/data
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  explorer-api:
    image: inputoutput/cardano-explorer-api:2.0.0
    depends_on:
      - postgres
      - dbsync
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    secrets:
      - postgres_password
      - postgres_user
      - postgres_db
    ports:
      - 8100:8100
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

  submit-api:
    image: inputoutput/cardano-submit-api:2.0.0
    environment:
      - NETWORK=mainnet
    depends_on:
      - node
    volumes:
      - cardano-node:/data
    ports:
      - 8101:8101
    restart: on-failure
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

secrets:
  postgres_db:
    file: ./config/postgres_db
  postgres_password:
    file: ./config/postgres_password
  postgres_user:
    file: ./config/postgres_user
  pgpass:
    file: ./config/pgpass

volumes:
  postgres:
  cardano-node:
```
