### ISSUE TITLE
LogRotation not working as expected

### ISSUE THREAD

**Issue by gufmar** [input-output-hk/cardano-node#992]
config files templates like https://github.com/input-output-hk/cardano-node/blob/master/configuration/defaults/byron-mainnet/configuration.yaml#L136 suggest 

```
rotation:
  rpLogLimitBytes: 10000000
  rpKeepFilesNum:  10
  rpMaxAgeHours:   24

```
the `rpLogLimitBytes` key seems to work as logfiles are created at that size.

I would expect `rpKeepFilesNum` to keep a maximum of 10 such files, and `rpMaxAgeHours` to sweep out all logfiles older than 24 hours.

So far, however, all log files remain in place.
